services:
  - type: web
    name: tucanobot
    env: node
    buildCommand: npm install --build-from-source
    startCommand: node index.js
    autoDeploy: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: NODE_VERSION
        value: "20.11.1"
      - key: SHARP_IGNORE_GLOBAL_LIBVIPS
        value: "1"
      - key: DATABASE_PATH
        value: "/data/database.sqlite"
    plan: free
    healthCheckPath: /
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - index.js
        - database/**
        - models/**
        - commands/**
        - events/**
        - utils/**
